### PR TITLE
Merge dev to master for 1.0.0-beta.5

### PR DESCRIPTION
**Pull request by philvarner**

### CODE REVIEW

**Review by cholmes — APPROVED** [review]

**Comment by m-mohr** [comment]
The CI fails I think we should fix that first.

**Comment by philvarner** [comment]
> The CI fails. I think we should fix that first.

Resolved. I thought I ran check as the last thing before merging the last PR, but I guess I made a couple of minor fixes with markdown errors after that.

**Comment by philvarner** [comment]
@m-mohr I'll wait for yours (or another approval) before merging and releasing

**Comment by philvarner** [comment]
@matthewhanson @m-mohr @jbants @lossyrob looking for another approval before merging.

**Review by lossyrob — APPROVED** [review]

**Pull request merged**
