### PR TITLE
Collections api

### PR DESCRIPTION
**Pull request by cholmes**
**Related Issue(s):** #

**Proposed Changes:**

1. Add collections as its own core STAC functionality.

**PR Checklist:**

- [ ] This PR is made against the dev branch (all proposed changes except releases should be against dev, not master).
- [ ] This PR has **no** breaking changes.
- [ ] I have added my changes to the [CHANGELOG](https://github.com/radiantearth/stac-api-spec/blob/dev/CHANGELOG.md) **or** a CHANGELOG entry is not required.
- [ ] OpenAPI files only: I have run `npm run generate-all` to update the [generated OpenAPI files](https://github.com/radiantearth/stac-api-spec/blob/dev/README.md#openapi-definitions).

### CODE REVIEW

**Comment by cholmes** [comment]
This still needs its openapi file.

**Comment by cholmes** [comment]
Be sure to point at a specific version of commons when we merge this. Though perhaps matters less if we're not actually depending on commons.

**Comment by philvarner** [comment]
Isn't /collections already part of STAC API - Feature?

**Comment by cholmes** [comment]
The idea for this was to have 'collections only' endpoints. Implementing features API requires items/ endpoints. It looked like OGC might have a clean way to do this in 'common', but then that wasn't as clean as we wanted.

**Comment by philvarner** [comment]
Added an Issue for this PR https://github.com/radiantearth/stac-api-spec/issues/134

**Comment by philvarner** [comment]
Created PR https://github.com/radiantearth/stac-api-spec/pull/179 to supersede this one

**Pull request closed without merging**
