### PR TITLE
Minor grammar corrections to overview.md

### PR DESCRIPTION
**Pull request by Kristianwhittick**
**Related Issue(s):** 

- Minor grammar corrections to overview.md

**Proposed Changes:**

1. Minor grammar corrections to overview.md 

**PR Checklist:**

- [X] This PR has **no** breaking changes.
- [X] This PR does not make any changes to the core spec in the `stac-spec` directory (these are included as a subtree and should be updated directly in [radiantearth/stac-spec](https://github.com/radiantearth/stac-spec))
- [Not Required ] I have added my changes to the [CHANGELOG](https://github.com/radiantearth/stac-api-spec/blob/dev/CHANGELOG.md) **or** a CHANGELOG entry is not required.

### CODE REVIEW

**Review by m-mohr — APPROVED** [review]

**Comment by m-mohr** [comment]
Thank you!

**Comment by Kristianwhittick** [comment]
@m-mohr - Who do I request to merge? I am not authorised.

**Comment by m-mohr** [comment]
It can be Phil or me, but the CI hasn't completed yet so waiting for that. Nothing to do on your side.

**Comment by philvarner** [comment]
PR was against master instead of main, changed.

**Pull request merged**
