### PR TITLE
add service-doc to core links table, add links diagram

### PR DESCRIPTION
**Pull request by philvarner**
**Related Issue(s):** #116

**Proposed Changes:**

1. add service-doc to Links page
2. add Links diagram

**PR Checklist:**

- [X] This PR is made against the dev branch (all proposed changes except releases should be against dev, not master).
- [X] This PR has **no** breaking changes.
- [X] I have added my changes to the [CHANGELOG](https://github.com/radiantearth/stac-api-spec/blob/dev/CHANGELOG.md) **or** a CHANGELOG entry is not required.

### CODE REVIEW

**Review by cholmes — APPROVED** [review]
Looks good. I think my only question with this is if we want to make service-desc and service doc to be 'optional' elements in the core spec? 

The reasoning would be that today if you wanted to include those right now you're supposed to fully implement the features API. Of course nothing would stop you from including them, so maybe it doesn't really matter. I think it'd just be a bit more endorsement to recommend people use it even if they're just implementing core + item-search.

**Comment by philvarner** [comment]
> Looks good. I think my only question with this is if we want to make service-desc and service doc to be 'optional' elements in the core spec?
> 
> The reasoning would be that today if you wanted to include those right now you're supposed to fully implement the features API. Of course nothing would stop you from including them, so maybe it doesn't really matter. I think it'd just be a bit more endorsement to recommend people use it even if they're just implementing core + item-search.

I think we want to at least recommend, if not require it -- it's just good practice, and we already have an openapi schema they can use for it.

I don't understand "if you wanted to include those right now you're supposed to fully implement the features API. " -- where is that required?

**Comment by m-mohr** [comment]
Those two rel types originate in OGC APIs and you have to implement them for being OGC API compliant.

For STAC core, which may just be a browsable catalog and not even have a OpenAPI, I'd highly recommend to not require it. I could see us recommending it, but feel more just giving the option and the implementor has to choose. I don't see them used often in clients so it may only be a "human" thing to look at these. From a RESTful point of view (and we claim being RESTful), OpenAPIs should actually not even be a thing as everything can be just retrieved from the links.

**Comment by philvarner** [comment]
> Those two rel types originate in OGC APIs and you have to implement them for being OGC API compliant.

This made me realize that we don't want this example Landing Page in core -- we should have one that is what you would see if you *only* implement core, e.g., no rel=search. We should also have these for the other 2, and then a 4th example of what a complete API that implements all 3 would look like.

**Pull request merged**
